# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      /blog/:title

# Server
source:         "."
destination:    ./_gh_pages
host:           0.0.0.0
port:           9001
baseurl:        ""
url:            "http://unquez.com"
encoding:       UTF-8
exclude:
  - .git/
  - .github/
  - node_modules/
  - nuget/
  - scss/
  - vendor/
  - src/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - yarn.json
  - README.md

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-paginate

title: UnQuez
description: "We create and design an awesome application"
paginate: 20
paginate_path: /blog/page-:num
